name: Publish NPM package

on:
  push:
    tags:
      - "*"
    paths:
      - "packages/code/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/code
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - run: pwd
      - run: ls -alh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: build-artifacts
          path: packages/code/.output

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/code
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          include-hidden-files: true
          name: build-artifacts
          path: packages/code/.output
      - name: Copy README.md from root
        run: |
          cp $GITHUB_WORKSPACE/README.md ./README.md
          cp $GITHUB_WORKSPACE/README.zh.md ./README.zh.md
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
